"""Compiler Agent — deterministic rendering to PDF/HTML.

Assembles approved memo sections into a Warba-branded document.
Uses Jinja2 templates for HTML generation and WeasyPrint for PDF conversion.

Design decision: The compiler is deterministic — no LLM involvement.
It simply renders the approved content with the bank's branding and formatting.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# HTML template for the memo
_MEMO_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Credit Memo - {{ client_name }}</title>
    <style>
        body { font-family: 'Inter', 'Roboto', sans-serif; margin: 0; padding: 20px; color: #333; }
        .header { background: #003366; color: white; padding: 30px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 28px; }
        .header .subtitle { color: #C9A227; margin-top: 5px; }
        .meta { display: flex; gap: 30px; margin-bottom: 20px; font-size: 14px; }
        .meta-item { padding: 10px; background: #f5f5f5; border-radius: 4px; }
        .meta-label { font-weight: bold; color: #003366; }
        .section { margin-bottom: 30px; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; }
        .section h2 { color: #003366; border-bottom: 2px solid #C9A227; padding-bottom: 8px; margin-top: 0; }
        .section-content { line-height: 1.6; }
        .flag { background: #fff3cd; padding: 8px 12px; border-radius: 4px; margin: 10px 0; border-left: 4px solid #C9A227; }
        .flag-error { background: #f8d7da; border-left-color: #dc3545; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; border-top: 1px solid #e0e0e0; }
        .ratios { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 15px 0; }
        .ratio-card { background: #f0f4f8; padding: 15px; border-radius: 8px; text-align: center; }
        .ratio-value { font-size: 24px; font-weight: bold; color: #003366; }
        .ratio-label { font-size: 12px; color: #666; margin-top: 5px; }
        .citation { color: #0066cc; font-size: 11px; cursor: pointer; }
        .approval-stamp { text-align: right; color: #28a745; font-weight: bold; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Credit Memo</h1>
        <div class="subtitle">{{ bank_name }} — {{ facility_type | title }} Facility</div>
    </div>

    <div class="meta">
        <div class="meta-item"><span class="meta-label">Client:</span> {{ client_name }}</div>
        <div class="meta-item"><span class="meta-label">Facility:</span> {{ facility_type | title }}</div>
        <div class="meta-item"><span class="meta-label">Value:</span> KD {{ deal_value | round | int | string }}</div>
        <div class="meta-item"><span class="meta-label">Date:</span> {{ generated_at }}</div>
        <div class="meta-item"><span class="meta-label">Status:</span> {{ status }}</div>
    </div>

    {% if ratios %}
    <div class="ratios">
        {% if ratios.dscr is not none %}
        <div class="ratio-card">
            <div class="ratio-value">{{ "%.2f" | format(ratios.dscr) }}x</div>
            <div class="ratio-label">DSCR</div>
        </div>
        {% endif %}
        {% if ratios.leverage_ratio is not none %}
        <div class="ratio-card">
            <div class="ratio-value">{{ "%.2f" | format(ratios.leverage_ratio) }}x</div>
            <div class="ratio-label">Leverage Ratio</div>
        </div>
        {% endif %}
        {% if ratios.current_ratio is not none %}
        <div class="ratio-card">
            <div class="ratio-value">{{ "%.2f" | format(ratios.current_ratio) }}x</div>
            <div class="ratio-label">Current Ratio</div>
        </div>
        {% endif %}
    </div>
    {% endif %}

    {% for section in sections %}
    <div class="section">
        <h2>{{ section.title }}</h2>
        <div class="section-content">{{ section.content }}</div>
        {% if section.flags %}
        {% for flag in section.flags %}
        <div class="flag {% if flag.severity == 'error' %}flag-error{% endif %}">
            <strong>{{ flag.severity | upper }}:</strong> {{ flag.detail }}
        </div>
        {% endfor %}
        {% endif %}
        {% if section.approved_by %}
        <div class="approval-stamp">Approved by {{ section.approved_by }}</div>
        {% endif %}
    </div>
    {% endfor %}

    <div class="footer">
        Generated by MemoForge — {{ bank_name }} | {{ generated_at }}<br>
        This document is confidential and intended for authorized personnel only.
    </div>
</body>
</html>"""


@dataclass
class CompilerResult:
    """Result from the compiler agent."""
    html_content: str = ""
    pdf_path: Optional[str] = None
    file_size_bytes: int = 0
    errors: List[str] = field(default_factory=list)


def run_compiler_agent(
    memo_id: str,
    client_name: str,
    facility_type: str,
    deal_value: float,
    sections: List[Dict[str, Any]],
    ratios: Optional[Dict[str, Any]] = None,
    output_dir: Optional[str] = None,
    generate_pdf: bool = True,
) -> CompilerResult:
    """Compile approved sections into a branded memo document.

    Args:
        memo_id: The memo identifier.
        client_name: Client display name.
        facility_type: Islamic facility type.
        deal_value: Deal value in KD.
        sections: List of section dicts with 'title', 'content', 'flags', 'approved_by'.
        ratios: Optional dict with ratio values.
        output_dir: Directory for output files.
        generate_pdf: Whether to generate PDF (requires WeasyPrint).

    Returns:
        CompilerResult with HTML content and optional PDF path.
    """
    from jinja2 import Template

    logger.info("CompilerAgent: compiling memo %s", memo_id)
    result = CompilerResult()

    template = Template(_MEMO_TEMPLATE)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = template.render(
        bank_name="Warba Bank",
        client_name=client_name or memo_id,
        facility_type=facility_type,
        deal_value=deal_value,
        generated_at=now,
        status="Finalized",
        sections=sections,
        ratios=ratios or {},
    )
    result.html_content = html

    # Save HTML
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        html_path = os.path.join(output_dir, f"memo_{memo_id}.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        result.file_size_bytes = len(html.encode("utf-8"))

        # Generate PDF if requested
        if generate_pdf:
            try:
                from weasyprint import HTML
                pdf_path = os.path.join(output_dir, f"memo_{memo_id}.pdf")
                HTML(string=html).write_pdf(pdf_path)
                result.pdf_path = pdf_path
                result.file_size_bytes = os.path.getsize(pdf_path)
                logger.info("CompilerAgent: PDF generated at %s", pdf_path)
            except ImportError:
                logger.warning("WeasyPrint not installed — skipping PDF generation")
                result.errors.append("PDF generation skipped: WeasyPrint not installed")
            except OSError as e:
                logger.warning("WeasyPrint system dependencies missing — skipping PDF: %s", e)
                result.errors.append(f"PDF generation skipped: system dependencies missing ({str(e)[:120]})")
                # Fall back: save HTML as the output document
                html_fallback = os.path.join(output_dir, f"memo_{memo_id}.html")
                if os.path.exists(html_fallback):
                    result.file_size_bytes = os.path.getsize(html_fallback)
                    logger.info("CompilerAgent: HTML fallback saved at %s", html_fallback)
            except Exception as e:
                logger.error("CompilerAgent: PDF generation failed: %s", e)
                result.errors.append(f"PDF generation failed: {str(e)[:200]}")

    return result
